name: "Pushed to branch"
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.137.2
        with:
          ruby-version: 3.2.0
          bundler: Gemfile.lock
          bundler-cache: true
      - name: Set up database schema
        run: bundle exec rails db:schema:load
      - name: Run tests
        run: bundle exec rake