name: "Pushed to branch"
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.137.2
        with:
          ruby-version: 3.2.1
          bundler: Gemfile.lock
          bundler-cache: true
      - name: Run tests
        run: |
          ls
          bundle exec rake